version: "2.1"

services:
    service: &service
        build: .
        links:
            - service.other
        environment:
            SERVICE_OTHER: service.other

    test:
        <<: *service
        command: go test -v -integration

    db:
        build: db/
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - ./var/mysql:/var/lib/mysql

    service.other:
        build: .
        links:
            - db
        environment:
            DATABASE_TYPE: mysql
            DATABASE_HOST: db
            DATABASE_PORT: 3306
            DATABASE_USER: service_other
            DATABASE_PASS: service_other
            DATABASE_DB: service_other
